### ISSUE TITLE
Include a tab counter / progress bar for each of the tabs

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/FAIR-DSM-Assessment-Tool#3]
- one needs to manually selected each of the 3 tabs to process.

- the next button is only meant to progress through the sub sections of the tabs but users have no indication of how many 'next' screen they will face.

**Comment by iemam** [comment]
Commited
https://github.com/FAIRplus/FAIR-DSM-Assessment-Tool/commit/25fed5e1e347e2a1240ac9a219a54ec547659470
